Сделано дз 2
kolike/code-and-magic pull request #2
Opened 2020-06-09 18:29 UTC by kolike

2020-06-09 20:14 UTC, KseniaFilippova requested changes

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +window.renderStatistics = function (ctx, players, times) {
players - отличное название) лучше чем names

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +  renderCloud(ctx, CLOUD_X + GAP, CLOUD_Y + GAP, "rgba(0, 0, 0, 0.7");
будет лучше вместо CLOUD_X + GAP, CLOUD_Y + GAP завести отдельные константы CLOUD_SHADOW_X , CLOUD_SHADOW_Y

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +  ctx.fillStyle = "#000";
зачем это?

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +var getMaxElement = function (arr) {
чотко

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +      CLOUD_X + GAP * 3 + (GAP_BETWEEN_BAR + BAR_WIDTH) * i, //но лучше выглядит - (CLOUD_WIDTH / players.length), равномернее
пиши комменты для нас сюда, как я, убери из кода)

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +    );
отступ)

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +    var randomTransparency = Math.floor(Math.random() * 10) / 10;
randomAlpha) и отступ
где код спиздил кста?

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +    if (players[i] == "Вы") {
можно вынести в константу ACTIVE_PLAYER

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +      ctx.fillStyle = `rgba(0, 0, 255, ${Math.random()})`;
randomTransparency не юзаешь вообще))

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +    }
отступ

2020-06-09 20:14 UTC, KseniaFilippova commented on js/stat.js
> +      Math.floor(times[i]),
скорее round, знаешь разницу?

2020-06-09 20:19 UTC, KseniaFilippova requested changes
В целом ты красава) Есть пара предложений как улучшить:

1) Из-за того что насыщенность синих столбцов может быть равна нулю, может возникнуть баг, когда колонка белого цвета: 
<img width="516" alt="Снимок экрана 2020-06-09 в 22 33 25" src="https://user-images.githubusercontent.com/44975231/84195401-2f6aa500-aaa7-11ea-9f93-4887c0b48557.png">
Предлагаю начинать насыщенность с 0.1

2) Чтобы код выглядел менее запутанным и лучше читался можно разделить логику из цикла на 3 функции: отрисовка имени, отрисовка столбца, отрисовка очков

2020-06-10 16:18 UTC, kolike commented on js/stat.js
> +window.renderStatistics = function (ctx, players, times) {
Это сарказм или реально лучше names? Я чет невдупляю)

2020-06-10 16:19 UTC, kolike commented on js/stat.js
> +  renderCloud(ctx, CLOUD_X + GAP, CLOUD_Y + GAP, "rgba(0, 0, 0, 0.7");
так я спецом и вводил GAP, типо разрыв, но как скажешь)

2020-06-10 16:23 UTC, kolike commented on js/stat.js
> +  ctx.fillStyle = "#000";
а если не написать, то текст белым пишет, я попробовал

2020-06-10 16:24 UTC, kolike commented on js/stat.js
> +var getMaxElement = function (arr) {
не понял)

2020-06-10 16:26 UTC, kolike commented on js/stat.js
> +    );
так отступ ")" то должен быть на уровне метода, который ее открыл, ctx.fillText, а у меня на уровне вроде

2020-06-10 16:29 UTC, kolike commented on js/stat.js
> +    var randomTransparency = Math.floor(Math.random() * 10) / 10;
randomAlpha - лучшее название переменной? 
если ты про переменную, то сам выдумал, как получить рандомное число 0<x<1.
А в общем, я не пиздил, по ходу лекции давали этот код, до определенного момента, потом я его доработал. Т.е. гистограмму сам вырисовывал

2020-06-10 16:29 UTC, kolike commented on js/stat.js
> +    if (players[i] == "Вы") {
хорошо)

2020-06-10 16:30 UTC, kolike commented on js/stat.js
> +      ctx.fillStyle = `rgba(0, 0, 255, ${Math.random()})`;
да у меня чет не получалось это рандомное говно сделать, я кучу способов перебрал, потом уже получилось так, а удалить переменную забыл)

2020-06-10 16:32 UTC, kolike commented on js/stat.js
> +    }
кста, поставил себе такую штуку, когда нажимаешь shift+alt+f, он редактирует код сам, типо точки с запятой выставляет и все отступы, тут говорит, что так надо))
но я поправлю

2020-06-10 16:33 UTC, kolike commented on js/stat.js
> +      Math.floor(times[i]),
ну да, округлить вниз
я не использовал round, чтоб "1" не получить, хотя, похоже ошибочно

2020-06-10 17:32 UTC, KseniaFilippova commented on js/stat.js
> +window.renderStatistics = function (ctx, players, times) {
А че сарказм то сразу? нам правда показалось удачнее)

2020-06-10 18:56 UTC, KseniaFilippova approved these changes

2020-06-10 18:56 UTC, KseniaFilippova commented on js/stat.js
> +    }
все замечания про вертикальные отступы, с горизонтальными все четко) если не делать пустые строки между блоками кода, функциями, все в кашу

2020-06-10 18:57 UTC, merged